# Generated by Django 4.2.20 on 2025-03-17 06:06

from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50)),
                ('unique_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('final_mark', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to=students.models.certificate_upload_path)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='programs.course')),
            ],
            options={
                'unique_together': {('course', 'email', 'serial_number')},
            },
        ),
    ]
