# Generated by Django 4.2.20 on 2025-03-17 06:06

from django.db import migrations, models
import django.db.models.deletion
import templates.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_file', models.FileField(upload_to=templates.models.template_upload_path)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='programs.course')),
            ],
            options={
                'unique_together': {('course', 'template_file')},
            },
        ),
    ]
