# Generated by Django 4.2.20 on 2025-06-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='unique_code',
        ),
    ]
