# Generated by Django 4.2.20 on 2025-06-04 12:32

from django.db import migrations, models
import django.db.models.deletion
import internship.models


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0002_remove_certificate_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to=internship.models.internship_certificate_upload_path),
        ),
        migrations.AlterUniqueTogether(
            name='certificate',
            unique_together={('intern', 'certificate_file')},
        ),
        migrations.CreateModel(
            name='InternshipCertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_file', models.FileField(upload_to=internship.models.internship_template_upload_path)),
                ('internship_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='internship.internshiprole')),
            ],
            options={
                'unique_together': {('internship_role', 'template_file')},
            },
        ),
    ]
