# Generated by Django 4.2.20 on 2025-06-04 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('internship', '0003_alter_certificate_certificate_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipcertificatetemplate',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificate_templates', to='internship.internshipbatch'),
        ),
        migrations.AddField(
            model_name='internshipcertificatetemplate',
            name='internship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificate_templates', to='internship.internship'),
        ),
        migrations.AlterField(
            model_name='internshipcertificatetemplate',
            name='internship_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certificate_templates', to='internship.internshiprole'),
        ),
    ]
